name: build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v6
        with:
          # 1.39.{19,20} hit a bug in clang: https://bugs.llvm.org/show_bug.cgi?id=46786
          version: 1.39.18
      - name: Verify
        run: emcc -v
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: make
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
